---
name: Transform collection
# yamllint disable-line rule:truthy
on:
  workflow_call:

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y rsync
          pip install ansible

      - name: Install dependency collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Transform collection
        env:
          GIT_REPOSITORY_BRANCH: ${{ github.ref_name }}
        run: |
          ansible-playbook build-collection.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: collection-tarball
          path: downstream/openshift_virtualization/redhat-openshift_virtualization-*.tar.gz
